const { initSidebar } = require('./js/sidebar');
const { initColorTool } = require('./js/tools/color');
const { initJsonTool } = require('./js/tools/json');
const { initCryptoTool } = require('./js/tools/crypto');
const { initCodeTool } = require('./js/tools/code');
const { initHttpTool } = require('./js/tools/http');
const { initRegexTool } = require('./js/tools/regex');
const { initTimeTool } = require('./js/tools/time');
const { initBaseTool } = require('./js/tools/base');
const { initImageTool } = require('./js/tools/image');
const { initQrcodeTool } = require('./js/tools/qrcode');
const { initGeneratorTool } = require('./js/tools/generator');
const { initMockTool } = require('./js/tools/mock');
const { initClockTool } = require('./js/tools/clock');
const { initNewsTool } = require('./js/tools/news');
const { initGitCheatsheet } = require('./js/tools/git-cheatsheet');
const { initAlgorithmVisualizer } = require('./js/tools/algorithm-visualizer');
const { initDesignPatterns } = require('./js/tools/design-patterns');
const { initLeetcodeDaily } = require('./js/tools/leetcode-daily');
const { initGithubTrending } = require('./js/tools/github-trending');
const { initTechDaily } = require('./js/tools/tech-daily');

document.addEventListener('DOMContentLoaded', () => {
  initSidebar();
  initColorTool();
  initJsonTool();
  initCryptoTool();
  initCodeTool();
  initHttpTool();
  initRegexTool();
  initTimeTool();
  initBaseTool();
  initImageTool();
  initQrcodeTool();
  initGeneratorTool();
  initMockTool();
  initClockTool();
  initNewsTool();
  initGitCheatsheet();
  initAlgorithmVisualizer();
  initDesignPatterns();
  initLeetcodeDaily();
  initGithubTrending();
  initTechDaily();
});
